# -*- coding: utf-8 -*-
"""data_analysis_visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HhjI7pGV0FhKrYNdJTNdCi9LI8M4v6gF
"""

import pandas as pd

import plotly.express as px

df1=pd.read_csv(r"/content/gene_expression.csv")
df1

# Select the gene you want to visualize (Line plots)
gene_name = 'GeneA'

# Create a new DataFrame with just the selected gene's data
df1_gene = df1[['Time', gene_name, 'Condition']].rename(columns={gene_name: 'Expression_Level'})

# Line plot for the specific gene over time
fig = px.line(df1_gene, x='Time', y='Expression_Level', color='Condition',
              title=f'Expression Levels of {gene_name} Over Time')
fig.update_layout(xaxis_title="Time", yaxis_title="Expression Level")
fig.show()

# Select the gene you want to visualize
gene_name = 'GeneB'

# Create a new DataFrame with just the selected gene's data
df1_gene = df1[['Time', gene_name, 'Condition']].rename(columns={gene_name: 'Expression_Level'})

# Line plot for the specific gene over time
fig = px.line(df1_gene, x='Time', y='Expression_Level', color='Condition',
              title=f'Expression Levels of {gene_name} Over Time')
fig.update_layout(xaxis_title="Time", yaxis_title="Expression Level")
fig.show()

# Select the gene you want to visualize
gene_name = 'GeneC'

# Create a new DataFrame with just the selected gene's data
df1_gene = df1[['Time', gene_name, 'Condition']].rename(columns={gene_name: 'Expression_Level'})

# Line plot for the specific gene over time
fig = px.line(df1_gene, x='Time', y='Expression_Level', color='Condition',
              title=f'Expression Levels of {gene_name} Over Time')
fig.update_layout(xaxis_title="Time", yaxis_title="Expression Level")
fig.show()

#Bar Chart
# Reshape the data to have 'Gene' and 'Expression_Level' columns for all genes
df1_melted = df1.melt(id_vars=['Time', 'Condition'], value_vars=['GeneA', 'GeneB', 'GeneC'],
                    var_name='Gene', value_name='Expression_Level')

# Calculate the average expression level for each gene across conditions
df1_avg = df1_melted.groupby(['Gene', 'Condition'])['Expression_Level'].mean().reset_index()

# Bar chart for average expression levels of each gene across conditions
fig = px.bar(df1_avg, x='Gene', y='Expression_Level', color='Condition', barmode='group',
             title='Average Expression Levels of Genes Across Conditions')
fig.update_layout(xaxis_title="Gene", yaxis_title="Average Expression Level")
fig.show()

#Histogram
df2=pd.read_csv(r"/content/patient_data - Sheet1.csv")
df2

# Plot histogram for age distribution
fig = px.histogram(df2, x='Age', nbins=10, title='Distribution of Patient Ages')
fig.update_layout(xaxis_title="Age", yaxis_title="Count")
fig.show()

df3=pd.read_csv(r"/content/clinical_trial_data - Sheet1 (1).csv")
df3

# Create a box plot to compare treatment outcomes between groups
fig = px.box(df3, x='Group', y='Outcome', title='Distribution of Treatment Outcomes by Group')
fig.update_layout(xaxis_title="Group", yaxis_title="Treatment Outcome")
fig.show()

fig = px.scatter(df2, x='Age', y='TreatmentOutcome',
                 title='Relationship between Patient Age and Treatment Outcome',
                 labels={'Age': 'Patient Age', 'TreatmentOutcome': 'Treatment Outcome'})
fig.update_layout(xaxis_title="Age", yaxis_title="Treatment Outcome")
fig.show()

# Reshape the data to make it suitable for a heatmap
df1_melted = df1.melt(id_vars=['Time', 'Condition'], value_vars=['GeneA', 'GeneB', 'GeneC'],
                    var_name='Gene', value_name='Expression_Level')

# Create a pivot table to arrange genes across samples for the heatmap
heatmap_data = df1_melted.pivot_table(index='Gene', columns='Time', values='Expression_Level')

# Plot heatmap
fig = px.imshow(heatmap_data, aspect='auto', color_continuous_scale='Viridis',
                title='Gene Expression Levels Across Samples')
fig.update_layout(xaxis_title="Time", yaxis_title="Gene")
fig.show()

df4=pd.read_csv(r"/content/protein_interaction_data - Sheet1.csv")
df4

import plotly.graph_objects as go

import networkx as nx

# Create a NetworkX graph from the protein interaction data
G = nx.from_pandas_edgelist(df4, 'Protein1', 'Protein2')

# Generate node positions using a layout algorithm
pos = nx.spring_layout(G)

# Extract node and edge information for Plotly
edge_x = []
edge_y = []
for edge in G.edges():
    x0, y0 = pos[edge[0]]
    x1, y1 = pos[edge[1]]
    edge_x.extend([x0, x1, None])
    edge_y.extend([y0, y1, None])

# Plot edges
edge_trace = go.Scatter(
    x=edge_x, y=edge_y,
    line=dict(width=4, color='blue'),
    hoverinfo='none',
    mode='lines')

# Plot nodes
node_x = []
node_y = []
node_text = []
for node in G.nodes():
    x, y = pos[node]
    node_x.append(x)
    node_y.append(y)
    node_text.append(node)

node_trace = go.Scatter(
    x=node_x, y=node_y,
    mode='markers+text',
    text=node_text,
    textposition="top center",
    marker=dict(size=20, color='orange', line_width=2))

# Create figure
fig = go.Figure(data=[edge_trace, node_trace],
                layout=go.Layout(
                    title="Protein-Protein Interaction Network",
                    showlegend=False,
                    xaxis=dict(showgrid=False, zeroline=False, range=[-1.2, 1.2]),
                    yaxis=dict(showgrid=False, zeroline=False, range=[-1.2, 1.2]))
               )

fig.show()

